name: trigger-prod-deployment

on:
  issues:
    types:
      - closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Run build script
        run: ./.github/scripts/issue.sh
        shell: bash
        env:
          EVENT: github.event.issue

