name: trigger-prod-deployment

on:
  issues:
    types:
      - closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Run build script
        run: |
          printenv
          #cat $GITHUB_EVENT_PATH
          echo '${{ toJson(github.event.issue) }}'
          curl comments_url
        shell: bash

