name: trigger-prod-deployment

on:
  issues:
    types:
      - closed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Run build script
        run: |
          printenv
          cat $GITHUB_EVENT_PATH
          echo '${{ github.event.issue.action }}'
        shell: bash

