name: deploy-bicep-production

on:
  workflow_dispatch:
    inputs:
      risk:
        type: boolean
        description: 'High risk deployment?'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      #Approval
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.TOKEN }}
        approvers: anbl-jyskebank-dk
        minimum-approvals: 1
        issue-title: "Approve production deployment, high risk: ${{ github.event.inputs.risk }}"
        exclude-workflow-initiator-as-approver: false

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        region: 'westeurope'
        template: ./main.bicep
        parameters: main.parameters-p.json
        failOnStdErr: true