name: deploy-bicep-production

on:
  workflow_dispatch:
    inputs:
      risk:
        type: boolean
        description: 'High risk deployment? \nOg en laaaang smøre om hvor farligt det er bla bla bla.\nNy linie bla bla'
      circumventSoD:
        type: boolean
        description: 'Do you want to deploy now and postpone approval(Not normal flow)?'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      #Approval
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.TOKEN }}
        approvers: rasmus-svith-andersen-jyskebank-dk, anbl-jyskebank-dk
        minimum-approvals: 1
        issue-title: "Approve production deployment, high risk: ${{ github.event.inputs.risk }}"
        exclude-workflow-initiator-as-approver: ${{ github.event.inputs.circumventSoD != 'true' }}

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        region: 'westeurope'
        template: ./main.bicep
        parameters: main.parameters-p.json
        failOnStdErr: true

    - uses: trstringer/manual-approval@v1
      if: ${{ github.event.inputs.circumventSoD == 'true' }}
      with:
        secret: ${{ secrets.TOKEN }}
        approvers: rasmus-svith-andersen-jyskebank-dk, anbl-jyskebank-dk
        minimum-approvals: 1
        issue-title: "Post approve production deployment, high risk: ${{ github.event.inputs.risk }}"
        exclude-workflow-initiator-as-approver: true